#-----------------------DB CONNECTION-----------------------
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/piris
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    database-change-log-lock-table: CHANGELOCK
    database-change-log-table: CHANGELOG
#-----------------------JPA ORM OPTIONS---------------------
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#------------------------SWAGGER-----------------------------
springdoc:
  packages-to-scan: by.zelezinsky.piris.controller
  swagger-ui:
    doc-expansion: none
    tagsSorter: alpha

